//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ma_start.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ma_start.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Game.
        /// </summary>
        public static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Help.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Load.
        /// </summary>
        public static string LoadHeroTitle {
            get {
                return ResourceManager.GetString("LoadHeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Annihilator.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Make.
        /// </summary>
        public static string MakeHeroTitle {
            get {
                return ResourceManager.GetString("MakeHeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Score.
        /// </summary>
        public static string ScoresTitle {
            get {
                return ResourceManager.GetString("ScoresTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Start.
        /// </summary>
        public static string StartTitle {
            get {
                return ResourceManager.GetString("StartTitle", resourceCulture);
            }
        }
    }
}
